# cloudbuild.yaml (Definitive, With Cleanup)
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA}', './backend']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: 'gcloud'
  args: [ 'run', 'deploy', 'sahara-backend-service', '--image=asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA}', '--region=asia-south1', '--service-account=sahara-app-backend-sa@${PROJECT_ID}.iam.gserviceaccount.com', '--allow-unauthenticated' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Clean Images'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud artifacts docker images delete asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA} --delete-tags --quiet || true
images:
- 'asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY