# cloudbuild.yaml (Simplified for Terraform-managed deployment)
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push'
    args:
      - 'build'
      - '--tag=asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA}'
      - './backend'
      - '--push'  # ✅ This builds and pushes in one step

images:
  - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/sahara-repo/sahara-backend:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
